unit HisService_Login_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, App_DAServer, 
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule,
  {Used RODLs:} DataAbstract4_Intf,
  {Generated:} HisLibrary_Intf;

type
  { THisService_Login }
  THisService_Login = class(TRORemoteDataModule, IHisService_Login)
  private
  protected
    { IHisService_Login methods }
    function Login(const LoginText: string): string;
    procedure Logout;
  end;

implementation

uses
  HisLibrary_Invk, HisService_System_Backend, uROClassFactories;

{$IFDEF DELPHIXE2UP}
{%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}

{$IFNDEF FPC}
  {$R *.dfm}
{$ELSE}
  {$R *.lfm}
{$ENDIF}

procedure Create_HisService_Login(out anInstance : IUnknown);
begin
  anInstance := THisService_Login.Create(nil);
end;

{ HisService_Login }
function THisService_Login.Login(const LoginText: string): string;
begin
  Result := SystemBackend.Login(Self, LoginText);
end;

procedure THisService_Login.Logout;
begin  
  SystemBackend.Logout(Self);
end;

var
  fClassFactory: IROClassFactory;
  
initialization
  fClassFactory := TROPooledClassFactory.Create('HisService_Login', {$IFDEF FPC}@{$ENDIF}Create_HisService_Login, THisService_Login_Invoker, 5);
  // RegisterForZeroConf(fClassFactory,'_HisService_Login_rosdk._tcp.');

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
