unit HisService_Dict_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, App_DAServer, HisService_Dict_Backend,
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule,
  {Ancestor Implementation:} DataAbstractService_Impl,
  {Used RODLs:} DataAbstract4_Intf,
  {Generated:} HisLibrary_Intf, uROClient, uDADataStreamer,
  uDABin2DataStreamer, uDAInterfaces, uDAFields, uDADelta, uROComponent,
  uDAJSONDataStreamer;

type
  { THisService_Dict }
  THisService_Dict = class(TDataAbstractService, IHisService_Dict)
    procedure DataAbstractServiceActivate(const aClientID: TGUID;
      aSession: TROSession; const aMessage: IROMessage);
    procedure DataAbstractServiceDeactivate(const aClientID: TGUID;
      aSession: TROSession);
    procedure DataAbstractServiceCreate(Sender: TObject);
    procedure DataAbstractServiceUpdateDataBeginTransaction(
      Sender: TObject; var aUseDefaultTransactionLogic: Boolean);
  private
  protected
    { IHisService_Dict methods }
  end;

implementation

{$IFDEF DELPHIXE2UP}
{%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}

{$IFNDEF FPC}
  {$R *.dfm}
{$ELSE}
  {$R *.lfm}
{$ENDIF}
uses
  {Generated:} HisLibrary_Invk, uROClassFactories;

procedure Create_HisService_Dict(out anInstance : IUnknown);
begin
  anInstance := THisService_Dict.Create(nil);
end;

var
  fClassFactory: IROClassFactory;

{ HisService_Dict }

procedure THisService_Dict.DataAbstractServiceActivate(
  const aClientID: TGUID; aSession: TROSession;
  const aMessage: IROMessage);
begin
  ServiceDataStreamer := DictBackend.GetDAStreamer;
  ServiceSchema := DictBackend.GetSchema;
end;

procedure THisService_Dict.DataAbstractServiceDeactivate(
  const aClientID: TGUID; aSession: TROSession);
begin
  ServiceSchema := nil;
end;

procedure THisService_Dict.DataAbstractServiceCreate(Sender: TObject);
begin
  AllowWhereSql := True;
end;

procedure THisService_Dict.DataAbstractServiceUpdateDataBeginTransaction(
  Sender: TObject; var aUseDefaultTransactionLogic: Boolean);
begin
  aUseDefaultTransactionLogic := False;
end;

initialization
  fClassFactory := TROPooledClassFactory.Create('HisService_Dict',
    {$IFDEF FPC}@{$ENDIF}Create_HisService_Dict, THisService_Dict_Invoker, 10);
  // RegisterForZeroConf(fClassFactory,'_HisService_Dict_rosdk._tcp.');

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
