unit HisService_Hosp_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, App_DAServer, HisService_Hosp_Backend,
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule,
  {Ancestor Implementation:} DataAbstractService_Impl,
  {Used RODLs:} DataAbstract4_Intf,
  {Generated:} HisLibrary_Intf, uROClient, uDADataStreamer,
  uDAInterfaces, uDAScriptingProvider, uDABusinessProcessor, uDABin2DataStreamer,
  uDAFields, uDADelta, uROComponent;

type
  { THisService_Hosp }
  THisService_Hosp = class(TDataAbstractService, IHisService_Hosp)
    procedure DataAbstractServiceActivate(const aClientID: TGUID;
      aSession: TROSession; const aMessage: IROMessage);
    procedure DataAbstractServiceDeactivate(const aClientID: TGUID;
      aSession: TROSession);
    procedure DataAbstractServiceUpdateDataBeginTransaction(
      Sender: TObject; var aUseDefaultTransactionLogic: Boolean);
  private
  protected
    { IHisService_Hosp methods }
  end;

implementation

{$IFDEF DELPHIXE2UP}
{%CLASSGROUP 'System.Classes.TPersistent'}
{$ENDIF}

{$IFNDEF FPC}
  {$R *.dfm}
{$ELSE}
  {$R *.lfm}
{$ENDIF}
uses
  {Generated:} HisLibrary_Invk, uROClassFactories;

procedure Create_HisService_Hosp(out anInstance : IUnknown);
begin
  anInstance := THisService_Hosp.Create(nil);
end;

var
  fClassFactory: IROClassFactory;

{ HisService_Hosp }

procedure THisService_Hosp.DataAbstractServiceActivate(
  const aClientID: TGUID; aSession: TROSession;
  const aMessage: IROMessage);
begin
  ServiceDataStreamer := HospBackend.GetDAStreamer;
  ServiceSchema := HospBackend.GetSchema;
end;

procedure THisService_Hosp.DataAbstractServiceDeactivate(
  const aClientID: TGUID; aSession: TROSession);
begin
  ServiceSchema := nil;
end;

procedure THisService_Hosp.DataAbstractServiceUpdateDataBeginTransaction(
  Sender: TObject; var aUseDefaultTransactionLogic: Boolean);
begin
  aUseDefaultTransactionLogic := False;
  //默认无事务，从而可在Command中修改远程服务器上的数据,而不需事务协调器
end;

initialization
  fClassFactory := TROPooledClassFactory.Create('HisService_Hosp',
    {$IFDEF FPC}@{$ENDIF}Create_HisService_Hosp, THisService_Hosp_Invoker, 10);
  // RegisterForZeroConf(fClassFactory,'_HisService_Hosp_rosdk._tcp.');

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
