unit IdeaLibrary_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf,
  {Used RODLs:} DataAbstract4_Intf;

const
  { Library ID }
  LibraryUID = '{8B809773-C57D-4F7F-AF9A-423284ABB852}';
  TargetNamespace = '';

  { Service Interface ID's }
  IIdeaService_IID : TGUID = '{460520E1-1C6B-436C-BC39-B5F857C60E96}';

type
  TSeekOrigin = Classes.TSeekOrigin; // fake declaration
  { Forward declarations }
  IIdeaService = interface;

  { IIdeaService }
  IIdeaService = interface(IDataAbstractService)
    ['{460520E1-1C6B-436C-BC39-B5F857C60E96}']
  end;

  { CoIdeaService }
  CoIdeaService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IIdeaService; overload;
    class function Create(const aUri: TROUri): IIdeaService; overload;
    class function Create(const aUrl: string): IIdeaService; overload;
  end;

  { TIdeaService_Proxy }
  TIdeaService_Proxy = class(TDataAbstractService_Proxy, IIdeaService)
  protected
    function __GetInterfaceName:string; override;

  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes, uROProxy;

{ CoIdeaService }

class function CoIdeaService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IIdeaService;
begin
  Result := TIdeaService_Proxy.Create(aMessage, aTransportChannel);
end;

class function CoIdeaService.Create(const aUri: TROUri): IIdeaService;
begin
  Result := TIdeaService_Proxy.Create(aUri, '');
end;

class function CoIdeaService.Create(const aUrl: string): IIdeaService;
begin
  Result := TIdeaService_Proxy.Create(aUrl, '');
end;

function TIdeaService_Proxy.__GetInterfaceName:string;
begin
  Result := 'IdeaService';
end;

initialization
  RegisterProxyClass(IIdeaService_IID, TIdeaService_Proxy);


finalization
  UnregisterProxyClass(IIdeaService_IID);


end.
