unit IdeaLibrary_Invk;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes,
  {RemObjects:} uROXMLIntf, uROServer, uROServerIntf, uROClasses, uROTypes, uROClientIntf,
  {Used RODL Intf's:} DataAbstract4_Intf,
  {Used RODL Invk's:} DataAbstract4_Invk,
  {Generated:} IdeaLibrary_Intf;

type
  TSeekOrigin = Classes.TSeekOrigin; // fake declaration
  TIdeaService_Invoker = class(TDataAbstractService_Invoker)
  private
  protected
  public
    constructor Create; override;
  published
  end;

implementation

uses
  {RemObjects:} uRORes, uROClient;

{ TIdeaService_Invoker }

constructor TIdeaService_Invoker.Create;
begin
  inherited Create;
  FAbstract := False;
end;

initialization
end.
