unit UpdateAppLib_Invk;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
//
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  uROEncoding,
  uROXMLIntf,
  uROServer,
  uROServerIntf,
  uROClasses,
  uROTypes,
  uROClientIntf,
  UpdateAppLib_Intf;

type
  { Forward declarations }
  TUpdateAppService_Invoker = class;

  TUpdateAppService_Invoker = class(TROInvoker)
  public
    constructor Create; override;
  published
    procedure Invoke_GetUpdateInfo(const __Instance: IInterface; const __Message: IROMessage; const __Transport: IROTransport; out __oResponseOptions: TROResponseOptions);
  end;

implementation

uses
  uROEventRepository,
  uRORes,
  uROClient;

constructor TUpdateAppService_Invoker.Create;
begin
  inherited Create();
  FAbstract := false;
end;

procedure TUpdateAppService_Invoker.Invoke_GetUpdateInfo(const __Instance: IInterface; const __Message: IROMessage; const __Transport: IROTransport; out __oResponseOptions: TROResponseOptions);
var
  l_AppInfo: string;
  lResult: string;
  __lintf: UpdateAppLib_Intf.IUpdateAppService;
begin
  CheckRoles(__Instance, GetDefaultServiceRoles());
  try
    if not Supports(__Instance, IUpdateAppService, __lintf) then begin
      raise EIntfCastError.Create('Critical error in TUpdateAppService_Invoker.Invoke_GetUpdateInfo: __Instance does not support UpdateAppService interface');
    end;

    __Message.Read('AppInfo', System.TypeInfo(string), l_AppInfo, [paAsUTF8String]);

    lResult := __lintf.GetUpdateInfo(l_AppInfo);

    __Message.InitializeResponseMessage(__Transport, 'UpdateAppLib', 'UpdateAppService', 'GetUpdateInfoResponse');
    __Message.Write('Result', System.TypeInfo(string), lResult, [paAsUTF8String]);
    __Message.Finalize();
    __Message.UnsetAttributes(__Transport);

  finally
    __lintf := nil;
  end;
end;

initialization
finalization
end.

