unit UpdateAppLib_Intf;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
//
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.TypInfo{$ELSE}TypInfo{$ENDIF},
  uROEncoding,
  uROUri,
  uROProxy,
  uROExceptions,
  uROXMLIntf,
  uROClasses,
  uROTypes,
  uROClientIntf,
  uROAsync,
  uROEventReceiver;

const LibraryUID: String = '{8320824B-4ABC-4D06-9B53-1BBF52E77D26}';
const DefaultNamespace: String = 'UpdateAppLib';
const TargetNamespace: String = 'UpdateAppLib';
const IUpdateAppService_IID: TGUID = '{D2E25A49-8369-43DF-B708-7946D7715279}';
type
  { Forward declarations }
  IUpdateAppService = interface;
  IUpdateAppService_Async = interface;
  IUpdateAppService_AsyncEx = interface;
  CoUpdateAppService = class;
  CoUpdateAppService_Async = class;
  CoUpdateAppService_AsyncEx = class;
  TUpdateAppService_Proxy = class;
  TUpdateAppService_AsyncProxy = class;
  TUpdateAppService_AsyncProxyEx = class;

  IUpdateAppService = interface(IROService)
  ['{D2E25A49-8369-43DF-B708-7946D7715279}']
    function GetUpdateInfo(const AppInfo: string): string;
  end;

  IUpdateAppService_Async = interface(IROAsyncInterface)
  ['{617C3FF5-456A-480E-A408-5CECAE4C8037}']
    procedure Invoke_GetUpdateInfo(const AppInfo: string);
    function Retrieve_GetUpdateInfo: string;
  end;

  IUpdateAppService_AsyncEx = interface(IROAsyncInterfaceEx)
  ['{A50867A6-399E-47A5-A385-4BCE16CC335C}']
    function BeginGetUpdateInfo(const AppInfo: string; const aCallback: TROAsyncCallback; const aUserData: Pointer = nil): IROAsyncRequest;
    function EndGetUpdateInfo(const aRequest: IROAsyncRequest): string;
  end;

  CoUpdateAppService = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService; overload;
  end;

  CoUpdateAppService_Async = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService_Async; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService_Async; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService_Async; overload;
  end;

  CoUpdateAppService_AsyncEx = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService_AsyncEx; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService_AsyncEx; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService_AsyncEx; overload;
  end;

  TUpdateAppService_Proxy = class(TROProxy, IUpdateAppService)
  protected
    function __GetInterfaceName: String; override;
    function GetUpdateInfo(const AppInfo: string): string;
  end;

  TUpdateAppService_AsyncProxy = class(TROAsyncProxy, IUpdateAppService_Async)
  protected
    function __GetInterfaceName: String; override;
    procedure Invoke_GetUpdateInfo(const AppInfo: string);
    function Retrieve_GetUpdateInfo: string;
  end;

  TUpdateAppService_AsyncProxyEx = class(TROAsyncProxyEx, IUpdateAppService_AsyncEx)
  protected
    function __GetInterfaceName: String; override;
    function BeginGetUpdateInfo(const AppInfo: string; const aCallback: TROAsyncCallback; const aUserData: Pointer = nil): IROAsyncRequest;
    function EndGetUpdateInfo(const aRequest: IROAsyncRequest): string;
  end;

function DefaultNamespaces: String;
implementation

uses
  uROSerializer,
  uROClient,
  uROTransportChannel,
  uRORes;

function DefaultNamespaces: String;
var
  lres: String;
begin
  lres := DefaultNamespace;
  result := lres;
  exit;
end;

type
  { Forward declarations }
  TMyTransportChannel = class;

  TMyTransportChannel = class(TROTransportChannel)
  end;

class function CoUpdateAppService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService;
begin
  result := TUpdateAppService_Proxy.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoUpdateAppService.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService;
begin
  result := TUpdateAppService_Proxy.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoUpdateAppService.Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService;
begin
  result := TUpdateAppService_Proxy.Create(aUrl, aDefaultNamespaces);
  exit;
end;

class function CoUpdateAppService_Async.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService_Async;
begin
  result := TUpdateAppService_AsyncProxy.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoUpdateAppService_Async.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService_Async;
begin
  result := TUpdateAppService_AsyncProxy.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoUpdateAppService_Async.Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService_Async;
begin
  result := TUpdateAppService_AsyncProxy.Create(aUrl, aDefaultNamespaces);
  exit;
end;

class function CoUpdateAppService_AsyncEx.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IUpdateAppService_AsyncEx;
begin
  result := TUpdateAppService_AsyncProxyEx.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoUpdateAppService_AsyncEx.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IUpdateAppService_AsyncEx;
begin
  result := TUpdateAppService_AsyncProxyEx.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoUpdateAppService_AsyncEx.Create(const aUrl: String; aDefaultNamespaces: String = ''): IUpdateAppService_AsyncEx;
begin
  result := TUpdateAppService_AsyncProxyEx.Create(aUrl, aDefaultNamespaces);
  exit;
end;

function TUpdateAppService_Proxy.__GetInterfaceName: String;
begin
  result := 'UpdateAppService';
  exit;
end;

function TUpdateAppService_Proxy.GetUpdateInfo(const AppInfo: string): string;
var
  lMessage: IROMessage;
  lTransportChannel: IROTransportChannel;
  lResult: string;
begin
  lMessage := __GetMessage();
  lMessage.SetAutoGeneratedNamespaces(DefaultNamespaces());
  lTransportChannel := __TransportChannel;
  try
    lMessage.InitializeRequestMessage(lTransportChannel, 'UpdateAppLib', __InterfaceName, 'GetUpdateInfo');
    lMessage.Write('AppInfo', System.TypeInfo(string), AppInfo, [paAsUTF8String]);
    lMessage.Finalize();

    lTransportChannel.Dispatch(lMessage);

    lMessage.Read('Result', System.TypeInfo(string), lResult, [paAsUTF8String]);
  finally
    lMessage.UnsetAttributes(lTransportChannel);
    lMessage.FreeStream();
    lMessage := nil;
    lTransportChannel := nil;
  end;
  result := lResult;
  exit;
end;

function TUpdateAppService_AsyncProxy.__GetInterfaceName: String;
begin
  result := 'UpdateAppService';
  exit;
end;

procedure TUpdateAppService_AsyncProxy.Invoke_GetUpdateInfo(const AppInfo: string);
var
  lMessage: IROMessage;
  lTransportChannel: IROTransportChannel;
begin
  lMessage := __GetMessage();
  lMessage.SetAutoGeneratedNamespaces(DefaultNamespaces());
  lTransportChannel := __TransportChannel;
  try
    __AssertProxyNotBusy('GetUpdateInfo');

    lMessage.InitializeRequestMessage(lTransportChannel, 'UpdateAppLib', __InterfaceName, 'GetUpdateInfo');
    lMessage.Write('AppInfo', System.TypeInfo(string), AppInfo, [paAsUTF8String]);
    __DispatchAsyncRequest('GetUpdateInfo', lMessage);
  finally
    lMessage.UnsetAttributes(lTransportChannel);
    lMessage := nil;
    lTransportChannel := nil;
  end;
end;

function TUpdateAppService_AsyncProxy.Retrieve_GetUpdateInfo: string;
var
  __response: TStream;
  tc: TMyTransportChannel;
  lRetry: Boolean;
  lMessage: IROMessage;
  lTransportChannel: IROTransportChannel;
  lFreeStream: Boolean;
  lResult: string;
begin
  lMessage := __GetMessage();
  lMessage.SetAutoGeneratedNamespaces(DefaultNamespaces());
  lTransportChannel := __TransportChannel;
  lFreeStream := false;
  try
    __response := __RetrieveAsyncResponse('GetUpdateInfo');
    try
      try
        try
          lMessage.ReadFromStream(__response, lFreeStream);
        except
          on E: Exception do begin
            lFreeStream := true;
            raise;
          end;
        end;

        lMessage.Read('Result', System.TypeInfo(string), lResult, [paAsUTF8String]);
      except
        on E: EROSessionNotFound do begin
          tc := TMyTransportChannel(lTransportChannel.GetTransportObject());
          lRetry := false;
          tc.DoLoginNeeded(lMessage, E, lRetry);
          if not lRetry then begin
            raise;
          end;
        end;
        on E: Exception do begin
          raise;
        end;
      end;
    finally
      if lFreeStream then begin
        __response.Free();
      end;
    end;
  finally
    lMessage := nil;
    lTransportChannel := nil;
  end;
  result := lResult;
  exit;
end;

function TUpdateAppService_AsyncProxyEx.__GetInterfaceName: String;
begin
  result := 'UpdateAppService';
  exit;
end;

function TUpdateAppService_AsyncProxyEx.BeginGetUpdateInfo(const AppInfo: string; const aCallback: TROAsyncCallback; const aUserData: Pointer = nil): IROAsyncRequest;
var
  lMessage: IROMessage;
  lTransportChannel: IROTransportChannel;
  lResult: IROAsyncRequest;
begin
  lMessage := __GetMessage();
  lMessage.SetAutoGeneratedNamespaces(DefaultNamespaces());
  lTransportChannel := __TransportChannel;
  try
    lMessage.InitializeRequestMessage(lTransportChannel, 'UpdateAppLib', __InterfaceName, 'GetUpdateInfo');
    lMessage.Write('AppInfo', System.TypeInfo(string), AppInfo, [paAsUTF8String]);
    lResult := __DispatchAsyncRequest(lMessage, aCallback, aUserData);
  finally
    lMessage := nil;
    lTransportChannel := nil;
  end;
  result := lResult;
  exit;
end;

function TUpdateAppService_AsyncProxyEx.EndGetUpdateInfo(const aRequest: IROAsyncRequest): string;
var
  lResult: string;
begin
  aRequest.ReadResponse();
  aRequest.Message.SetAutoGeneratedNamespaces(DefaultNamespaces());
  aRequest.Message.Read('Result', System.TypeInfo(string), lResult, [paAsUTF8String]);
  result := lResult;
  exit;
end;

initialization
  RegisterProxyClass(IUpdateAppService_IID, TUpdateAppService_Proxy);
finalization
  UnregisterProxyClass(IUpdateAppService_IID);
end.

